const instructionDetails = {
  INSTRUCTION_DOSELECT: "Instructions from DoSelect",
  ENJOY_BEST_EXP: "To enjoy the best experience on our platform. please ensure that",
  ASSESSMENT_INVITATION_SENT: "The assessment invitation was sent to the email address",
  USER_EMAIL: "samir@hutechsolutions.com",
  PLACEHOLDER: "Full Name",
  ENTER_DETAILS: "Please enter some details to proceed.",
  T_AND_C: "By proceeding, you are agreeing to our Terms of Service and Privacy Policy",
  ISREQUIRED: " is required!",
  PROCEED: "Confirm and Proceed",
  SAMPLE_ASSESSMENT: "Sample Assessment",
  ASSESSMENT_RECOMMENDATION:
    "We recommend that you take the sample assessment before starting your actual assessment. to get familiar with our environment.",
  CLICK_HERE: "Click here",
  TO_TAKE_SAMPLE: "to take our sample assessment. Please use password: sample to proceed.",
  NOTE: " Note You will be allowed to take this sample assessment only if you are a first time user.",
  ASSESSMENT_INSTRUCTION: "Assessment Instructions",
  CONTINUE: "Continue",
  BACK: "Back",
  INSTRUCTION: "Instructions",
  SYSTEM_CHECK: "System Check",
  IDENTITY_CHECK: "Identity Check",
  PASSED: "Passed",
  CHECKING: "Checking ...",
  TEST_SYSTEM: "Test your audio & Video",
  IDENTITY_INFO:
    "This assessment requires you to take an image of yourself to be used for proctoring purposes, Please ensure the following before taking the image.",
  TAKE_SNAPSHOT: "Take Snapshot",
  CHECKBOX_TXT:
    "I hereby declare that I have not impersonated, or allowed myself to be impersonated by any person for the purposes of this assessment. All work submitted in this assessment will be my own work and does not involve plagiarism or teamwork.",
  AGREE_AND_CONT: "Agree  &  Continue ",
  BACK_TO_INSTR: "Back to Instructions",
  SUBMIT_AND_NEXT: "Submit Section & Move to next section",
  FINISH_AND_SUBMIT: "Finish and Submit Assessment",
  ARE_U_SURE: "Are you sure?",
  STILL_HAVE: "You still have ",
  REMAIN_TIME: "2 hours 47 minutes 32 seconds ",
  TIME_LEFT: " left to submit this assessment.",
  ATTEMPTED: " You have attempted 7 out of 8 questions.",
  SURE_TO_SUBMIT:
    "You will not be able to attempt any question or make changes to your solutions once you submit.",
  CANCEL: "Cancel",
  SUBMIT_END: "Submit and end the Assessment",
  ALT_IMG: "icon Doselect",
  BTN_TYPE: "button",
  INTERNET_SPEED: "High internet Speed",
  DUMMY_SPEED_DATA: "40.895 mbps download,27.685 mbps upload-looks good!",
  OS: " Opreating System",
  BROWSER: "Browser",
  SOUND: "Sound",
  CHECK_SOUND: "Check Sound",
  PLAY_TO_HEAR: "Play this sound, do you hear it?",
  PLAY_SOUND: "Play Sound",
  ID_MYAUDIO: "myAudio",
  AUDIO_TYPE_OGG: "audio/ogg",
  AUDIO_TYPE_MPEG: "audio/ogg",
  MICROPHONE: "Microphone",
  CHK_MIC: " Check Microphone",
  MAKE_SOUND: " Make sound, are the bars are moving?",
  VIDEO: "Video",
  WIN11_OR_LATER: "11 or later",
  WINDOWS: "Windows",
  PF_VERSION: "platformVersion",
  CHK_VIDEO: " Check Video",
  CHK_CAM: "Can you see yourself in camera?",
  CAM_OFF: "Camera is off",
  APP_VIDEO_FEED: "app__videoFeed",
  CANVASID_IDENTITY_CHK: "canvasId",
  CANVAS_DIMENSION: "2d",
  BTN_ID: "buttonId",
  STEPS_TITLE_1: "Instructions",
  STEPS_TITLE_2: "System Check",
  STEPS_TITLE_3: "Identity",
  INTERNAL_SPEAKERS_LABEL: "Internal Speakers",
  INTERNAL_CAMERA_LABEL: "Internal Camera",
  INTERNAL_MICROPHONE_LABEL: "Internal  Microphone",
  MBPS: " mbps download",
  LOW_SPEED: " mbps download - slow internet detected",
  FORM_LAYOUT: "vertical",
  ROW_KEY: "SlNo",
  COL_KEY_1: "Sl.No",
  COL_TITLE_2: "Problem Name",
  COL_KEY_2: "ProblemName",
  COL_TITLE_3: "Problem Category",
  COL_KEY_3: "ProblemCategory",
  STATUS: "Status",
  UNSOLVED: "UNSOLVED",
  SOLVING: "SOLVING",
  SOLVED: "SOLVED",
  ACTIONS: "Action",
  SOLVE: "SOLVE",
  RESUME: "RESUME",
  REJECTED: "REJECTED",
  REVIEW: "REVIEW",
  DEFAULT_SPEAK: "Default speakers",
  DEFAULT_MIC: "Default microphone",
  DEFAULT_CAM: "Default camera",
  TEST_URL: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Brandenburger_Tor_abends.jpg",
  TO_DATA_URL: "image/png",
  USER_IMG_PATH: "data:image/png;base64,",
  SPACE_DIRECTION: "vertical",
  HTML_TYPE: "submit",
  VISUALIZER: {
    CREATEELEMENTNS: "http://www.w3.org/2000/svg",
    MAIN_VISUAL_DIV: "mainvisualdiv",
    PATH: "path",
    VISUALIZER_ID: "visualizer",
    MASK: "mask",
    VIEWBOX: "viewBox",
    STROKE_DASH: "stroke-dasharray",
    MASKGROUP: "maskGroup",
    GRADIENT: "gradient",
    FILL: "url(#gradient)",
    MASK_CLR: "url(#mask)",
    WIDTH_HEIGHT: "100%"
  }
};
export default instructionDetails;
